CREATE TABLE T_PRODUCT_CONFIG(
				 VTYPE 			VARCHAR(32) PRIMARY KEY
				,PICNAME		VARCHAR(32)
				,WIDTH 			INTEGER
				,HEIGHT 		INTEGER
				,MINCOUNT 		INTEGER
				,PRODUCTNAME 	VARCHAR(64)
				,RED 			INTEGER
				,GREEN 			INTEGER
				,BLUE 			INTEGER
);
SELECT  VTYPE,PICNAME,WIDTH,HEIGHT,MINCOUNT,PRODUCTNAME,RED,GREEN,BLUE FROM  T_PRODUCT_CONFIG;	
INSERT INTO T_PRODUCT_CONFIG(VTYPE,PICNAME,WIDTH,HEIGHT,MINCOUNT,PRODUCTNAME,RED,GREEN,BLUE)
 VALUES('01','方便面.png',50,50,3,'方便面',221,221,0);	
 INSERT INTO T_PRODUCT_CONFIG(VTYPE,PICNAME,WIDTH,HEIGHT,MINCOUNT,PRODUCTNAME,RED,GREEN,BLUE)
 VALUES(@VTYPE,@PICNAME,@WIDTH,@HEIGHT,@MINCOUNT,@PRODUCTNAME,@RED,@GREEN,@BLUE);	
 
 UPDATE T_PRODUCT_CONFIG set PICNAME=@PICNAME,WIDTH=@WIDTH,HEIGHT=@HEIGHT
 ,MINCOUNT=@MINCOUNT,PRODUCTNAME=@PRODUCTNAME,RED=@RED,GREEN=@GREEN,BLUE=@BLUE)
  WHERE VTYPE= @VTYPE;
 
DELETE FROM T_PRODUCT_CONFIG WHERE VTYPE= @VTYPE;

CREATE TABLE 商品类别表(
	[商品名称] [nchar](30) PRIMARY KEY NOT NULL,
	[单价] [numeric](18, 5) NULL,
	[备注] [nvarchar](500) NULL,
	[位置] [nchar](100) NULL,
	[图片] [nchar](100) NULL,
	[所属类别] [nchar](100) NULL
)
